### ISSUE TITLE
[Request] List Users/Examples

### ISSUE THREAD

**Issue by NielsPilgaard** [getsentry/probot-config#29]
Hello!

I'm having a hard time wrapping my head around how I would implement probot-config for my user, so I would love to be able to see how others have done it. I suggest appending a list of a few known users of probot-config to the README, if said users volunteer. Would that be possible?

**Comment by gr2m** [comment]
That’s a great idea :) I use `probot-config` in the WIP app: https://github.com/wip/app/blob/b427eee3be7f71d3729b57f413edf0462ce9ec5b/lib/pro/get-config.js

I also documented configuration for users: 
https://github.com/wip/app#configuration

Hope that helps?
